services: 
  - type: web 
    name: workloghub-api 
    runtime: docker 
    region: oregon 
    plan: free 
    envVars: 
      - key: SPRING_PROFILES_ACTIVE 
        value: prod 
      - key: PORT 
        value: 8080 
      - key: DB_HOST 
        fromDatabase: 
          name: workloghub-db 
          property: host 
      - key: DB_PORT 
        fromDatabase: 
          name: workloghub-db 
          property: port 
      - key: DB_NAME 
        fromDatabase: 
          name: workloghub-db 
          property: database 
      - key: SPRING_DATASOURCE_USERNAME 
        fromDatabase: 
          name: workloghub-db 
          property: user 
      - key: SPRING_DATASOURCE_PASSWORD 
        fromDatabase: 
          name: workloghub-db 
          property: password 
      - key: CORS_ORIGINS 
        value: https://workloghub.vercel.app 
 
databases: 
  - name: workloghub-db 
    plan: free
